EVENTS = {
  hello: 'HelloEventData',
  ready: 'ReadyEventData',
  resumed: 'ResumedEventData',
  channel_create: 'Channel',
  channel_update: 'Channel',
  channel_delete: 'Channel',
  channel_pins_update: 'ChannelPinsUpdateEventData',
  guild_create: 'Guild',
  guild_update: 'Guild',
  guild_delete: 'UnavailableGuild',
  guild_ban_add: 'UserWithGuildId',
  guild_ban_remove: 'UserWithGuildId',
  guild_emojis_update: 'GuildEmojisUpdateEventData',
  guild_integrations_update: 'GuildIntegrationsUpdateEventData',
  guild_member_add: 'GuildMemberWithGuildId',
  guild_member_remove: 'GuildMemberRemoveEventData',
  guild_member_update: 'GuildMemberUpdateEventData',
  guild_members_chunk: 'GuildMembersChunkEventData',
  typing_start: 'TypingStartEventData'
}